export { default as authReducer } from "./auth/authSlice";
export { default as designReducer } from "./designManagement/designManagementSlice";
export { default as usersReducer } from "./admin/adminsSlice";
export { default as customersReducer } from "./customer/customersSlice";
export { default as foodsReducer } from "./foods/foodsSlice";
export { default as ordersReducer } from "./orders/ordersSlice";
export { default as customSalesReducer } from "./customSales/customSalesSlice";
export { default as agentRequestsReducer } from "./agentRequests/agentRequestsSlice";
export { default as agentsReducer } from "./agents/agentsSlice";